WebMVC/Models/LoginViewModel.cs
using Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models
{
    public class LoginViewModel
    {
        public List<TipoUsuario> ListaTipos => Enum.GetValues(typeof(TipoUsuario)).Cast<TipoUsuario>()
                .Where(a => a != TipoUsuario.Administrador && a != TipoUsuario.Entregador).ToList();

        public PessoaFisica PessoaFisica { get; set; }
        public PessoaJuridica PessoaJuridica { get; set; }
        public Usuario Usuario { get; set; }
        public Endereco Endereco { get; set; }
    }
}

WebMVC/Areas/Identity/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebMVC.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

WebMVC/Controllers/CorreiosController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Domain.Validate;
using Domain.ViaCEP;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebMVC.Controllers
{
    public class CorreiosController : Controller
    {
        /// <summary>
        /// The base URL
        /// </summary>
        private const String BaseUrl = "https://viacep.com.br";


        public async Task<JsonResult> BuscarCEP(string zipCode)
        {
            if (Validacao.Cep(zipCode))
            {
                //try
                //{
                //    return Json(SearchAsync(zipCode, CancellationToken.None, null).Result);
                //}
                //catch
                //{
                //    return Json(SearchAsync(zipCode, CancellationToken.None, GetHandler()).Result);
                //}

                var cep = await PegarCEP(zipCode);

                return new JsonResult(cep);
            }

            return new JsonResult(false);
        }


        private HttpClientHandler GetHandler()
        {
            var proxyUrl = @"http://smapro-cl1:9090";
            var proxyUsername = @"alanbarros";
            var proxyPassword = @"Winterwolf3647";
            var proxyDomain = @"sma.local";
            var authType = "NTLM";

            var credCache = new CredentialCache();
            var credentials = new NetworkCredential(proxyUsername, proxyPassword, proxyDomain);
            credCache.Add(new Uri(proxyUrl), authType, credentials);

            return new HttpClientHandler
            {
                UseProxy = true,
                Proxy = new WebProxy
                {
                    Address = new Uri(proxyUrl),
                    Credentials = credCache
                }
            };
        }

        /*private async Task<ViaCEPResult> SearchAsync(String zipCode, CancellationToken token, HttpClientHandler handler)
        {
            using (var client = handler is null ? new HttpClient() : new HttpClient(handler))
            {
                client.BaseAddress = new Uri(BaseUrl);

                var resp2 = await client.GetAsync($"/ws/{zipCode}/json/");
                var response = await client.GetAsync($"/ws/{zipCode}/json/", token).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                var viacep = response.Content.ReadAsAsync<ViaCEPResult>(token).ConfigureAwait(false);
                return await viacep;
            }
        }*/

        private async Task<ResultViaCEP> PegarCEP(string cep)
        {
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);

                var response = await client.GetAsync($"/ws/{cep}/json/");

                var resultado = new ResultViaCEP();
                if (response.StatusCode == HttpStatusCode.OK)
                {
                    string conteudo = await response.Content.ReadAsStringAsync();
                    resultado = JsonConvert.DeserializeObject<ResultViaCEP>(conteudo);
                }
                return resultado;
            }
        }
    }

    public class ResultViaCEP
    {
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
        public string unidade { get; set; }
        public string ibge { get; set; }
        public string gia { get; set; }
    }
}

WebMVC/Controllers/LoginController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services.Contratos;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginServices services;
        private readonly string SessionCarrinho = "_Carrinho";

        public LoginController(ILoginServices Services)
        {
            services = Services;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Logon(Usuario usuario)
        {
            if (usuario.Username == null || usuario.Password == null) return View("Index",usuario);

            try
            {
                var claims = services.Autenticar(usuario);
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(new ClaimsPrincipal(identity),
                    new AuthenticationProperties { ExpiresUtc = DateTime.UtcNow.AddDays(8) });
            }
            catch
            {
                ModelState.AddModelError("Username", "Usuario ou senha inválidos");
                return View("Index");
            }

            return Redirect("~/");
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.SetString(SessionCarrinho, "");
            await HttpContext.SignOutAsync();
            return Redirect("~/");
        }

        public IActionResult CriarNovo()
        {
            var model = new LoginViewModel()
            {
                Endereco = new Endereco(),
                PessoaFisica = new PessoaFisica(),
                PessoaJuridica = new PessoaJuridica(),
                Usuario = new Usuario()
            };

            return View(model);
        }
    }
}

WebMVC/Controllers/VitrineLojaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Data;
using WebMVC.Models;
using Services.Contratos;

namespace WebMVC.Controllers
{
    public class VitrineLojaController : Controller
    {
        private readonly LojaDBContext _context;
        private readonly ILoginServices _services;
        private readonly IProdutoServices produtoServices;

        public VitrineLojaController(LojaDBContext context, ILoginServices services, IProdutoServices produtoServices)
        {
            _context = context;
            _services = services;
            this.produtoServices = produtoServices;
        }

        public async Task<IActionResult> Index()
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = await produtoServices.GetProdutosAsync(),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View(vitrine);
        }

        public async Task<IActionResult> IndexByIdComerciante(int? id)
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = produtoServices.GetProdutos(id.Value),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            var categoria = produtoServices.GetCategoriaProdutoByIdComerciante(id.Value);

            ViewBag.Categorias = _context.CategoriaProdutos.ToList().Where<CategoriaProduto>(c => c.IdComerciante == id.Value);

            return View(vitrine);
        }

        public async Task<IActionResult> IndexByIdCategoria(int? id)
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = produtoServices.GetProdutosByCategoria(id.Value),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View(vitrine);
        }

        public ActionResult<List<Produto>> BuscarProduto(string nomeProduto)
        {
            var lista = _context.Produtos.Where(a => a.Nome.Contains(nomeProduto)).ToList();
            return new JsonResult(lista);
        }

        public async Task<IActionResult> ExibirBuscaProdutos(string nomeProduto)
        {
            nomeProduto = nomeProduto ?? "";

            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = (await produtoServices.GetProdutosAsync()).Where(a => a.Nome.ToLower().Contains(nomeProduto.ToLower())).ToList(),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.GetUsuarioLogadoAsync(User);
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View("Index",vitrine);
        }

        public async Task<ActionResult> VerProduto(int? id)
        {
            if (id.HasValue)
            {
                var vitrine = new VitrineLojaViewModel()
                {
                    Produto = await produtoServices.GetProdutoAsync(id.Value)
                };

                vitrine.Produto.Categoria = produtoServices.GetCategoriaProduto(vitrine.Produto.IdCategoria);

                vitrine.Produto.Comerciante = produtoServices.GetComercianteProduto(vitrine.Produto.IdComerciante);

                if (vitrine.Produto != null) return View(vitrine.Produto); else return Redirect("/");
            }
            return Redirect("/");
        }
        
    }
}

WebMVC/Views/Login/CriarNovo.cshtml
@model WebMVC.Models.LoginViewModel

@{
    ViewData["Title"] = "CriarNovo";
    Layout = "~/Views/Shared/_Login.cshtml";
}

<label asp-for="Usuario.TipoUsuario" class="control-label"></label>
<select class="form-control" id="tipoUser" asp-items="@new SelectList(Model.ListaTipos)" onchange="MostrarFormulario()">
    <option selected="selected" value=""></option>
</select>

<div id="formUser" hidden>
    <partial name="_FormUsuario" model="@Model.Usuario" />
    <div id="formPF" hidden>
        <partial name="_FormPF" model="@Model" />
    </div>
    <div id="formPJ" hidden>
        <partial name="_FormPJ" model="@Model" />
    </div>
    <partial name="_FormEndereco" model="@Model.Endereco" />
    <button class="btn btn-success" id="cadastrar"><i class="fa fa-save"></i> Cadastrar</button>
    <button class="btn btn-danger" id="voltar"><i class="fa fa-home"></i> Home</button>
</div>

<script src="~/js/classes.js"></script>
<script type="text/javascript">
    function MostrarFormulario()
    {
        switch ($("#tipoUser").val()) {
            case "Comerciante":
                habilitarPJ();
                break;
            case "Consumidor":
                habilitarPF();
                break;
            case "Entregador":
                habilitarPF();
                break;
            default: ocultarTodos();
        }
        $("input").removeClass("is-invalid");
        $("select").removeClass("is-invalid");
    }
    function habilitarPJ()
    {
        $("#formUser").removeAttr("hidden", true);
        $("#formPJ").removeAttr("hidden");
        $("#formPF").attr("hidden", true);
    }
    function habilitarPF() {
        $("#formUser").removeAttr("hidden", true);
        $("#formPF").removeAttr("hidden");
        $("#formPJ").attr("hidden", true);
    }

    function TipoUsuario(tipo) {
        switch (tipo) {
            case "Comerciante":
                return "PJ";
                break;
            case "Consumidor":
                return "PF";
                break;
            case "Entregador":
                return "PF";
                break;
        }
    }

    function ocultarTodos() {
        $("#formUser").attr("hidden", true);
    }

    $("#voltar").click(function () {
        window.location.href = '@Url.Action("Index","VitrineLoja")';
    });

    $("#cadastrar").click(function () {
        var user = ["Username", "Password", "Email", "RepitaPassword","CEP", "Municipio", "UF", "Logradouro", "Numero", "Bairro"];
        var pf = ["PessoaFisica_Cpf", "PessoaFisica_NomeCompleto", "PessoaFisica_DataNascimento", "PessoaFisica_Telefone", "PessoaFisica_Sexo"];
        var pj = ["PessoaJuridica_Cnpj", "PessoaJuridica_RazaoSocial", "PessoaJuridica_NomeFantasia", "PessoaJuridica_Segmento","PessoaJuridica_Telefone"];

        var erros = 0;

        var senha1 = $("#RepitaPassword").val();
        var senha2 = $("#Password").val();

        erros += ValidaCampos(user);
        var tipo = TipoUsuario($("#tipoUser").val());


        if (senha1 != senha2) {
            alert("As senhas são diferentes");
            return;
        } else {
            if (tipo == "PF") {
                erros += ValidaCampos(pf);
            } else {
                erros += ValidaCampos(pj);
            }

            if (erros > 0) {
                alert("Contém erros");
            } else {
                AjaxEnviar(tipo);
            }
        }
    });

    function AjaxEnviar(tipo) {
        var url;
        var pessoa;

        var usuario = new Usuario($("#Username").val(), $("#Password").val(), $("#Email").val(), $("#RepitaPassword").val(), $("#tipoUser").val());
        var endereco = new Endereco($("#CEP").val(), $("#Municipio").val(), $("#UF").val(), $("#Logradouro").val(), $("#Numero").val(), $("#Bairro").val());

        if (tipo == "PF") {
            url = '@Url.Action("Cadastrar","PessoaFisicas")';
            pessoa = new PessoaFisica($("#PessoaFisica_Cpf").val(), $("#PessoaFisica_NomeCompleto").val(), $("#PessoaFisica_DataNascimento").val(), $("#PessoaFisica_Sexo").val(), $("#PessoaFisica_Telefone").val());
            pessoa.Usuario = usuario;
            pessoa.Endereco = endereco;
        } else {
            url = '@Url.Action("Cadastrar","PessoaJuridicas")';
            pessoa = new PessoaJuridica($("#PessoaJuridica_Cnpj").val(), $("#PessoaJuridica_RazaoSocial").val(), $("#PessoaJuridica_NomeFantasia").val(), $("#PessoaJuridica_Segmento").val(), $("#PessoaJuridica_Telefone").val());
            pessoa.Usuario = usuario;
            pessoa.Endereco = endereco;
        }

        $.post(url, pessoa, function (data) {
            switch (data.tipoUsuario) {
                case 0: // Consumidor
                    window.location.href = '@Url.Action("Index","VitrineLoja")';
                    break;
                case 1: // Comerciante
                    window.location.href = '@Url.Action("Index","VitrineLoja")';
                    break;
                case 2: // Entregador
                    window.location.href = '@Url.Action("Index","VitrineLoja")';
                    break;
                case 3: // Administrador
                    window.location.href = '@Url.Action("Index","VitrineLoja")';
                    break;
                default:
                    alert("Resulado inesperado...");
            }
        }).done(function () {
            //alert("Funcionou!");
        }).fail(function () {
            alert("Falhou!");
        }).always(function () {
            //alert("Acabou");
        });
    }

    function ValidaCampos(campos) {
        var erros = 0;

        for (var i = 0; i < campos.length; i++) {
            if ($("#" + campos[i]).val() == "") {
                $("#" + campos[i]).addClass("is-invalid");
                erros++;
            } else {
                $("#" + campos[i]).removeClass("is-invalid");
            }
        }

        return erros;
    }

    function buscarUsuario()
    {
        var _username = $("#Username").val();
        $.ajax({
            url: '@Url.Action("BuscarUsuario", "PessoaFisicas")',
            type: 'GET',
            contentType: "application/json",
            data: { Username: _username },
            success: function (result) {
                if (result.value == null) {
                    $("#Username").removeClass("is-invalid");
                    $("#Username").addClass("is-valid");
                    $("#cadastrar").removeAttr("disabled");
                } else {
                    $("#Username").removeClass("is-valid");
                    $("#Username").addClass("is-invalid");
                    $("#userInvalido").html(result.value);
                    $("#cadastrar").attr("disabled", true);
                }
            },
            error: function (xhr, exception) {
                alert("Erro ao buscar Usuário")
            }
        });
    }

    function buscarCPF()
    {
        var _cpf = $("#PessoaFisica_Cpf").val();
        $.ajax({
            url: '@Url.Action("BuscarCPF","PessoaFisicas")',
            type: 'GET',
            contentType: "application/json",
            data: { CPF: _cpf },
            success: function (result) {
                if (result.value == null) {
                    $("#PessoaFisica_Cpf").removeClass("is-invalid");
                    $("#PessoaFisica_Cpf").addClass("is-valid");
                    $("#cadastrar").removeAttr("disabled");
                } else {
                    $("#PessoaFisica_Cpf").removeClass("is-valid");
                    $("#PessoaFisica_Cpf").addClass("is-invalid");
                    $("#cpfInvalido").html(result.value);
                    $("#cadastrar").attr("disabled", true);
                }
            },
            error: function (xhr, exception) {
                alert("Erro ao buscar CPF")
            }
        });
    }

    function buscarCEP() {
        var cep = $("#CEP").val();
        $.ajax({
            url: '@Url.Action("BuscarCEP","Correios")',
            type: "GET",
            contentType: "application/json",
            data: { zipCode: cep },
            success: function (result) {
                if (result) {
                    $("#Logradouro").val(result.logradouro);
                    $("#Municipio").val(result.localidade);
                    $("#UF").val(result.uf);
                    $("#Bairro").val(result.bairro);
                    $("#CEP").removeClass("is-invalid");
                } else {
                    $("#CEP").addClass("is-invalid");
                }
            },
            error: function (xhr, exception) {
                alert("Erro ao buscar CEP!")
            }
        });
    }
</script>

WebMVC/Views/Login/Index.cshtml
@model Domain.Models.Usuario
@{
    Layout = null;
    var n = new Random().Next(1, 13);
    var bgclass = "big-background" + n;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Nextmart Inc.&reg; Tudo o que você precisa, simples e rápido!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body class="@bgclass">
    <div class="row center-box">
        <div class="col-md-4 center-form form-box">
            <form method="post" asp-action="Logon">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username" class="control-label"></label>
                    <input asp-for="Username" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Entrar" class="btn btn-success" />
                    <a asp-controller="Login" asp-action="CriarNovo" class="btn btn-primary"><i class="fa fa-plus"></i> Novo</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

WebMVC/Views/Login/_FormEndereco.cshtml
@model Domain.Models.Endereco

<div class="form-row">
    <div class="form-group col-md-4">
        <label asp-for="CEP" class="control-label"></label>
        <input asp-for="CEP" class="form-control" onblur="buscarCEP()" />
    </div>
    <div class="form-group col-md-6">
        <label asp-for="Municipio" class="control-label"></label>
        <input asp-for="Municipio" class="form-control" />
    </div>
    <div class="form-group col-md-2">
        <label asp-for="UF" class="control-label"></label>
        <select asp-for="UF" class="form-control" asp-items="new SelectList(@Model.GetUFs())">
            <option selected></option>
        </select>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-9">
        <label asp-for="Logradouro" class="control-label"></label>
        <input asp-for="Logradouro" class="form-control" />
    </div>
    <div class="form-group col-md-3">
        <label asp-for="Numero" class="control-label"></label>
        <input asp-for="Numero" class="form-control" />
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label asp-for="Complemento" class="control-label"></label>
        <input asp-for="Complemento" class="form-control" />
    </div>
    <div class="form-group col-md-6">
        <label asp-for="Bairro" class="control-label"></label>
        <input asp-for="Bairro" class="form-control" />
    </div>
</div>

WebMVC/Views/Login/_FormPF.cshtml
@model WebMVC.Models.LoginViewModel

<div class="row" id="formPF">
    <div class="col-md-12">
        <div class="form-row">
            <div class="form-group col-md-4">
                <label asp-for="PessoaFisica.Cpf" class="control-label"></label>
                <input asp-for="PessoaFisica.Cpf" class="form-control" onblur="buscarCPF()" type="number" />
                <div class="valid-feedback">
                    CPF válido!
                </div>
                <div class="invalid-feedback" id="cpfInvalido"></div>
            </div>
            <div class="form-group col-md-8">
                <label asp-for="PessoaFisica.NomeCompleto" class="control-label"></label>
                <input asp-for="PessoaFisica.NomeCompleto" class="form-control" />
                <span asp-validation-for="PessoaFisica.NomeCompleto" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">

            <div class="form-group col-md-4">
                <label asp-for="PessoaFisica.DataNascimento" class="control-label"></label>
                <input asp-for="PessoaFisica.DataNascimento" class="form-control" />
                <span asp-validation-for="PessoaFisica.DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="PessoaFisica.Sexo" class="control-label"></label>
                <select asp-for="PessoaFisica.Sexo" class="form-control" asp-items="new SelectList(@Model.PessoaFisica.GetSexos())">
                    <option selected></option>
                </select>
                <span asp-validation-for="PessoaFisica.Sexo" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="PessoaFisica.Telefone" class="control-label"></label>
                <input asp-for="PessoaFisica.Telefone" class="form-control" />
                <span asp-validation-for="PessoaFisica.Telefone" class="text-danger"></span>
            </div>
        </div>
    </div>
</div>

WebMVC/Views/Login/_FormPJ.cshtml
@model WebMVC.Models.LoginViewModel

<div class="row">
    <div class="col-md-12">
        <div class="form-row">
            <div class="form-group col-md-4">
                <label asp-for="PessoaJuridica.Cnpj" class="control-label"></label>
                <input asp-for="PessoaJuridica.Cnpj" class="form-control" />
                <span asp-validation-for="PessoaJuridica.Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group col-md-8">
                <label asp-for="PessoaJuridica.RazaoSocial" class="control-label"></label>
                <input asp-for="PessoaJuridica.RazaoSocial" class="form-control" />
                <span asp-validation-for="PessoaJuridica.RazaoSocial" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="PessoaJuridica.NomeFantasia" class="control-label"></label>
                <input asp-for="PessoaJuridica.NomeFantasia" class="form-control" />
                <span asp-validation-for="PessoaJuridica.NomeFantasia" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="PessoaJuridica.Segmento" class="control-label"></label>
                <input asp-for="PessoaJuridica.Segmento" class="form-control" />
                <span asp-validation-for="PessoaJuridica.Segmento" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="PessoaJuridica.Telefone" class="control-label"></label>
                <input asp-for="PessoaJuridica.Telefone" class="form-control" />
                <span asp-validation-for="PessoaJuridica.Telefone" class="text-danger"></span>
            </div>
        </div>
    </div>
</div>

WebMVC/Views/Login/_FormUsuario.cshtml
@model Domain.Models.Usuario

<div class="row" id="fomularioUsuario">
    <div class="col-md-12">
        <div class="form-row">
            <div class="form-group col-md-3">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" onblur="buscarUsuario()" />
                <div class="valid-feedback">
                    Usuário válido!
                </div>
                <div class="invalid-feedback" id="userInvalido"></div>
            </div>
            <div class="form-group col-md-5">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group col-md-2">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
            </div>
            <div class="form-group col-md-2">
                <label asp-for="RepitaPassword" class="control-label"></label>
                <input asp-for="RepitaPassword" class="form-control" />
            </div>
        </div>
    </div>
</div>