WebMVC/Models/LoginViewModel.cs
using Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models
{
    public class LoginViewModel
    {
        public List<TipoUsuario> ListaTipos => Enum.GetValues(typeof(TipoUsuario)).Cast<TipoUsuario>()
                .Where(a => a != TipoUsuario.Administrador && a != TipoUsuario.Entregador).ToList();

        public PessoaFisica PessoaFisica { get; set; }
        public PessoaJuridica PessoaJuridica { get; set; }
        public Usuario Usuario { get; set; }
        public Endereco Endereco { get; set; }
    }
}

WebMVC/Areas/Identity/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebMVC.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl = returnUrl ?? Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

WebMVC/Controllers/AdminController.cs
using System.Linq;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Data;
using WebMVC.Models;
using Services.Contratos;
using System.Threading.Tasks;

namespace WebMVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly LojaDBContext context;
        private readonly IVendaServices vendaServices;
        private readonly ILoginServices loginServices;

        public AdminController(LojaDBContext context, IVendaServices vendaServices, ILoginServices loginServices)
        {
            this.context = context;
            this.vendaServices = vendaServices;
            this.loginServices = loginServices;
        }

        // GET: Admin
        public ActionResult Index()
        {
            var model = new AdministradorViewModel();
            model.Tarifas = context.Tarifas.ToList();
            return View(model);
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.Find(id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        [HttpPost]
        public ActionResult CadastroTarifa(Tarifa tarifa)
        {
            if (ModelState.IsValid)
            {
                context.Tarifas.Add(tarifa);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult CadastroTarifa()
        {
            return View();
        }

        public PartialViewResult ListaTarifas()
        {
            var model = new AdministradorViewModel();
            model.Tarifas = context.Tarifas.ToList();
            return PartialView("_listaTarifas", model.Tarifas);
        }
        
        public async Task<PartialViewResult> ListaVendas()
        {
            var model = new AdministradorViewModel();
            model.Vendas = await vendaServices.GetAllVendas();
            model.ObterLucro();

            return PartialView("_listaVendas", model.Vendas);
        }

        public async Task<PartialViewResult> AllVendas()
        {
            var model = new AdministradorViewModel();
            model.Vendas = await vendaServices.GetAllVendas();

            return PartialView("_allVendas", model.Vendas);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.Find(id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tarifa tarifa)
        {            
            if (id != tarifa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(tarifa);
                    context.SaveChanges();
                }
                catch 
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.FirstOrDefault(t => t.Id == id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // POST: Admin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var tarifa = context.Tarifas.Find(id);
            context.Tarifas.Remove(tarifa);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));        
        }

        // GET: Admin/DeleteVenda/5
        public async Task<ActionResult> DeleteVenda(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await vendaServices.GetVendaByIdAsync(id.Value);

            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Admin/DeleteVenda/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteVenda(int id)
        {
            var venda = vendaServices.GetVendaById(id);
            await vendaServices.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/LoginController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services.Contratos;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILoginServices services;
        private readonly string SessionCarrinho = "_Carrinho";

        public LoginController(ILoginServices Services)
        {
            services = Services;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Logon(Usuario usuario)
        {
            if (usuario.Username == null || usuario.Password == null) return View("Index",usuario);

            try
            {
                var claims = services.Autenticar(usuario);
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(new ClaimsPrincipal(identity),
                    new AuthenticationProperties { ExpiresUtc = DateTime.UtcNow.AddDays(8) });
            }
            catch
            {
                ModelState.AddModelError("Username", "Usuario ou senha inválidos");
                return View("Index");
            }

            return Redirect("~/");
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.SetString(SessionCarrinho, "");
            await HttpContext.SignOutAsync();
            return Redirect("~/");
        }

        public IActionResult CriarNovo()
        {
            var model = new LoginViewModel()
            {
                Endereco = new Endereco(),
                PessoaFisica = new PessoaFisica(),
                PessoaJuridica = new PessoaJuridica(),
                Usuario = new Usuario()
            };

            return View(model);
        }
    }
}

WebMVC/Controllers/LojasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.Data;
using Services.Contratos;

namespace WebMVC.Controllers
{
    [Authorize]
    public class LojasController : Controller
    {
        private readonly ILoginServices _services;
        private readonly LojaDBContext _context;

        public LojasController(LojaDBContext context, ILoginServices services)
        {
            _context = context;
            _services = services;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public JsonResult GetEnderecos(string idLojas)
        {
            var listaEnderecos = new List<string>();
            
            var endereco = _context.Enderecos.Find(Convert.ToInt32(idLojas));
            var enderecoString = endereco.Logradouro + " " + endereco.Numero + ", " + endereco.CEP;
            listaEnderecos.Add(enderecoString);

            return Json(listaEnderecos);
        }

        public JsonResult GetLojas()
        {
            var listaString = new List<string>();

            var listaLojas = _context.PessoasJuridicas.ToList();

            foreach (var l in listaLojas)
            {
                var idLoja = l.Id.ToString() ;
                listaString.Add(idLoja);
            }

            return Json(listaString);
        }

        public JsonResult GetInfo(string idLojas)
        {
            var pessoaJuridica = _context.PessoasJuridicas.Find(Convert.ToInt32(idLojas));

            var enderecoLoja = _context.Enderecos.FirstOrDefault(a => a.Id == pessoaJuridica.IdEndereco);

            pessoaJuridica.Endereco = enderecoLoja;

            return Json(pessoaJuridica);
        }

        public JsonResult GetProdutos(string idLojas)
        {
            var produtos = new List<CategoriaProduto>();

            var pessoaJuridica = _context.PessoasJuridicas.Find(Convert.ToInt32(idLojas));

            if (pessoaJuridica is null)
            {
                return null;
            }

            produtos = _context.CategoriaProdutos.Where(a => a.IdComerciante == pessoaJuridica.Id).Take(5).ToList();

            return Json(produtos);
        }
    }
}

WebMVC/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contratos;

namespace WebMVC.Controllers
{
    [Authorize(Roles = "Consumidor")]
    public class PedidosController : Controller
    {
        private readonly IVendaServices vendaServices;
        private readonly ILoginServices loginServices;
        private readonly IPessoaServices pessoaServices;
        private readonly IProdutoServices produtoServices;

        public PedidosController(IVendaServices vendaServices, ILoginServices loginServices, IPessoaServices pessoaServices, IProdutoServices produtoServices)
        {
            this.vendaServices = vendaServices;
            this.pessoaServices = pessoaServices;
            this.loginServices = loginServices;
            this.produtoServices = produtoServices;
        }

        public async Task<IActionResult> Index()
        {
            var user = await loginServices.GetUsuarioLogadoAsync(User);
            var vendas = vendaServices.GetVendasByIdUsuario(user.Id);
            return View(vendas);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var venda = await vendaServices.GetVendaByIdAsync(Id);
            return View(venda);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var venda = await vendaServices.GetVendaByIdAsync(Id);

            if (venda.StatusVenda != StatusVenda.Concluida)
            {
                await produtoServices.Restock(venda.Itens);
                await vendaServices.RemoveAsync(Id);
            }
            else
            {
                await vendaServices.RemoveAsync(Id);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> ItemUpdate(Item item)
        {
            if (item is null) return null;
            item = await vendaServices.UpdateItemAsync(item);
            var venda = await vendaServices.GetVendaByIdAsync(item.VendaId);

            return new JsonResult(venda.GetValorTotal());
        }

        [HttpPost]
        public async Task<IActionResult> ItemDelete(Item item)
        {
            if(await vendaServices.RemoveItemAsync(item.Id))
            {
                var venda = await vendaServices.GetVendaByIdAsync(item.VendaId);
                return new JsonResult(venda.GetValorTotal());
            }
            return BadRequest();
        }

        public async Task<IActionResult> Pagar(int idVenda)
        {
            var venda = await vendaServices.GetVendaByIdAsync(idVenda);

            venda = await vendaServices.PagarAsync(venda);

            if (venda.StatusVenda == StatusVenda.Aberta)
            {
                return View("FalhaPagamento", venda);
            }
            else
            {
                return View(venda);
            }            
        }
    }
}

WebMVC/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contratos;

namespace WebMVC.Controllers
{
    [Authorize(Roles = "Comerciante")]
    public class VendasController : Controller
    {
        private readonly IVendaServices vendaServices;
        private readonly ILoginServices loginServices;

        public VendasController(IVendaServices vendaServices, ILoginServices loginServices)
        {
            this.vendaServices = vendaServices;
            this.loginServices = loginServices;
        }

        public async Task<IActionResult> Index()
        {
            var user = await loginServices.GetUsuarioLogadoAsync(User);
            var pessoa = await loginServices.RetornaPessoaPeloUsuarioAsync(user);

            var itensvendidos = await vendaServices.ItensVendidos(pessoa as PessoaJuridica);

            return View(itensvendidos);
        }
    }
}

WebMVC/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/img/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/img/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/img/favicons/favicon-16x16.png">
<link rel="manifest" href="~/img/favicons/site.webmanifest">
<link rel="mask-icon" href="~/img/favicons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

WebMVC/Views/Shared/_Footer.cshtml
<div class="col-md-12" style="display:flex">
    <div class="col-md-11">
        <div class="container">
            Nextmart Inc.&reg; Tudo o que você precisa, simples e rápido! &copy; <a>Todos os direitos reservados</a>
        </div>
    </div>
    <div class="col-md-1 version"><a asp-action="Index" asp-controller="Admin">Open Beta 0.8.14</a></div>
</div>

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nextmart Inc.&reg; Tudo o que você precisa, simples e rápido!</title>
    <partial name="_Favicons" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/lightbox.min.css" />
    <!-- Owl Stylesheets -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <!-- Owl javascript -->
    <!-- Não retirar da head -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/owl.carousel.js"></script>
    <script src="~/js/highlight.js"></script>
    <script src="~/js/app.js"></script>
    <!-- Owl javascript -->
    <script type="text/javascript" src="~/js/menuscript.js"></script>
</head>
<body>
    <header>
        <partial name="_NavbarNextmart" />
    </header>
    <main role="main">
        <div class="col-md-12 content1">
            @if (User.Identity.IsAuthenticated)
            {<partial name="_Menu" />}
             <div class="container">
                 @RenderBody()
             </div>
        </div>
    </main>
    <footer id="rodape" class="border-top footer text-muted bg-light">
        <partial name="_Footer" />
    </footer>

    <!-- Scripts -->
    <script type="text/javascript" src="~/js/lightbox-plus-jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
</body>
</html>

WebMVC/Views/Shared/_Login.cshtml
@{ 
    var n = new Random().Next(1, 8);
    var bgclass = "big-background" + n;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body class="@bgclass">
    <div class="row center-box">
        <div class="col-md-8 center-form form-box">
            @RenderBody()
        </div>
    </div>
</body>
</html>

WebMVC/Views/Shared/_Menu.cshtml
<div class="menu bg-dark">
    <div class="menu-header bg-secondary menu-propit">
        <a><h2>@User.Identity.Name</h2></a>
    </div>
    @if (User.IsInRole("Consumidor"))
    {
        <div class="menu-body menu-propit">
            <div class="menu-box">
                <a asp-action="Index" asp-controller="Lojas" class="menu-item"><i class="fa fa-shopping-basket"></i> <div>Lojas</div></a>
            </div>
            <div class="menu-box">
                <a asp-action="Index" asp-controller="VitrineLoja" class="menu-item"><i class="fa fa-dropbox"></i> <div>Produtos</div></a>
            </div>

            <div class="menu-box">
                <a asp-action="Index" asp-controller="Pedidos" class="menu-item"><i class="fa fa-shopping-bag"></i> <div>Pedidos</div></a>
            </div>

            <div class="menu-box">
                <a asp-action="Carteira" asp-controller="PessoaFisicas" class="menu-item"><i class="fa fa-dollar"></i> <div>Carteira</div></a>
            </div>
        </div>
    }
    @if (User.IsInRole("Comerciante"))
    {
        <div class="menu-body menu-propit">
            <div class="menu-box">
                <a asp-action="Index" asp-controller="Produtos" class="menu-item"><i class="fa fa-dropbox"></i> <div>Produtos</div></a>
            </div>
            <div class="menu-box">
                <a asp-action="Index" asp-controller="CategoriaProdutos" class="menu-item"><i class="fa fa-search"></i> <div>Categorias</div></a>
            </div>
            <div class="menu-box">
                <a asp-action="Index" asp-controller="Vendas" class="menu-item"><i class="fa fa-shopping-bag"></i> <div>Itens Vendidos</div></a>
            </div>
            <div class="menu-box">
                <a asp-action="Carteira" asp-controller="PessoaJuridicas" class="menu-item"><i class="fa fa-dollar"></i> <div>Carteira</div></a>
            </div>
        </div>
    }
</div>

WebMVC/Views/Shared/_NavbarNextmart.cshtml
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    @if (User.Identity.IsAuthenticated)
    {
        <button class="navbar-toggle btn btn-outline-light menu-show">
            <span class="fa fa-bars"></span>
        </button>
    }
    <a class="navbar-brand" href="/"><img src="~/img/logo v2b.png" class="logo" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    @{
        <div class="collapse navbar-collapse" id="navbarCollapse" align="right">
            <div class="collapse-box">
                <div class="form-inline total-right ls" align="right">
                    <div class="form-inline mr-sm-2">
                        <div class="input-group">
                            <input id="Produtos" class="form-control" placeholder="Buscar Produto" aria-label="Buscar Produto" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-light" type="button" onclick="BuscarProdutos()" id="button-addon2">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    @if (!User.IsInRole("Comerciante"))
                    {
                        <a asp-action="Index" asp-controller="Carrinho" class="btn btn-outline-light my-2 my-sm-0"><i class="fa fa-shopping-cart"></i> Carrinho</a>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">
                            <a asp-action="Index" asp-controller="Login" class="btn btn-outline-primary my-2 my-sm-0 " id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> @User.Identity.Name</a>
                            @if (User.IsInRole("Consumidor"))
                            {
                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                    <a asp-action="Details" asp-controller="PessoaFisicas" class="dropdown-item"><i class="fa fa-info-circle"></i> Perfil</a>
                                    <a asp-action="EditUsuario" asp-controller="PessoaFisicas" class="dropdown-item"><i class="fa fa-key"></i> Segurança</a>
                                </div>
                            }
                            @if (User.IsInRole("Comerciante"))
                            {
                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                    <a asp-action="Details" asp-controller="PessoaJuridicas" class="dropdown-item"><i class="fa fa-info-circle"></i> Perfil</a>
                                    <a asp-action="EditUsuario" asp-controller="PessoaJuridicas" class="dropdown-item"><i class="fa fa-key"></i> Segurança</a>
                                </div>
                            }
                            <a asp-action="Logout" asp-controller="Login" class="btn btn-outline-danger my-2 my-sm-0"><i class="fa fa-sign-out"></i> Sair</a>
                        </div>
                    }
                    else
                    {
                        <a asp-action="Index" asp-controller="Login" class="btn btn-outline-success my-2 my-sm-0"><i class="fa fa-sign-out"></i> Login</a>
                    }
                </div>
            </div>
        </div>
    }
</nav>

<div id="tabela" class="col-md-5 tabela-produtos mt-1"></div>

<script>
    $("#Produtos").keyup(function (e) {
        $.ajax({
            method: "GET",
            url: '@Url.Action("BuscarProduto","VitrineLoja")',
            data: { nomeProduto: $("#Produtos").val()}
        })
            .done(function (data) {
                $("#tabela").empty();

                $.each(data, function (index, valor) {
                    $("#tabela").append("<div class='alert alert-dark'><a href='/VitrineLoja/VerProduto/"+valor.id+"'>" + valor.nome + "</a></div>");
                })
            });

        if(e.which == 13) {
            BuscarProdutos();
        }
    });

    function BuscarProdutos() {
        var url = "/VitrineLoja/ExibirBuscaProdutos?nomeProduto=" + $("#Produtos").val();
        window.location.replace(url);
    }

</script>

WebMVC/Views/Shared/_ScriptLayoutBasico.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>