WebMVC/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Services.Contratos;

namespace WebMVC.Controllers
{
    public class CarrinhoController : Controller
    {
        CultureInfo ptBR = new CultureInfo("pt-BR");    

        private readonly IVendaServices vendaServices;
        private readonly IProdutoServices produtoServices;
        private readonly IPessoaServices pessoaServices;
        private readonly ILoginServices loginServices;
        public const string SessionCarrinho = "_Carrinho";

        public CarrinhoController(IVendaServices vendaServices, IProdutoServices produtoServices, IPessoaServices pessoaServices, ILoginServices loginServices)
        {
            this.produtoServices = produtoServices;
            this.vendaServices = vendaServices;
            this.pessoaServices = pessoaServices;
            this.loginServices = loginServices;
        }

        public IActionResult ObterJsonCarrinho()
        {
            return new JsonResult(ObterItensCarrinho(GetCarrinhoSessao()));
        }

        public IActionResult Index()
        {
            var itens = ObterItensCarrinho(GetCarrinhoSessao());

            return View(itens);
        }

        private Carrinho GetCarrinhoSessao()
        {
            var result = HttpContext.Session.GetString(SessionCarrinho) ?? "";
            return JsonConvert.DeserializeObject<Carrinho>(result);
        }

        private List<Item> ObterItensCarrinho(Carrinho carrinho)
        {
            if (carrinho is null) return new List<Item>();

            var itens = new List<Item>();

            carrinho.Itens.ForEach(item =>
            {
                var produto = produtoServices.GetProduto(item.IdProduto);           

                            
            itens.Add(new Item { ProdutoId = item.IdProduto, Quantidade = item.Quantidade, ValorUnidade = item.Valor, Produto = produto });

            });


            //var v = (String.Format(new CultureInfo("pt-BR"), "{0:C}", itens).ToList);

            return itens;
        }

        [HttpPost]
        public IActionResult AdicionarItem(ItemCarrinho item)
        {
            var carrinho = GetCarrinhoSessao();

            if(carrinho is null)
            {
                var itens = new List<ItemCarrinho> { item };
                HttpContext.Session.SetString(SessionCarrinho, JsonConvert.SerializeObject(new Carrinho { Itens = itens }));
            } else
            {
                carrinho = InsereItemNoCarrinho(item, carrinho);

                HttpContext.Session.SetString(SessionCarrinho, 
                    JsonConvert.SerializeObject(carrinho));
            }
            return new JsonResult(ObterItensCarrinho(carrinho));
        }

        [HttpPost]
        public IActionResult EditItem(ItemCarrinho item)
        {
            var carrinho = GetCarrinhoSessao();

            if (carrinho is null)
            {
                var itens = new List<ItemCarrinho> { item };
                HttpContext.Session.SetString(SessionCarrinho, JsonConvert.SerializeObject(new Carrinho { Itens = itens }));
            }
            else
            {
                carrinho = EditarItemCarrinho(item, carrinho);

                HttpContext.Session.SetString(SessionCarrinho,
                    JsonConvert.SerializeObject(carrinho));
            }
            return new JsonResult(ObterItensCarrinho(carrinho));
        }

        public async Task<IActionResult> EditarItem(int id)
        {
            var carrinho = GetCarrinhoSessao();

            if (carrinho is null)
            {
                return NotFound();
            }

            var itemCarrinho = carrinho.Itens.FirstOrDefault(p => p.IdProduto == id);
            var _item = new Item
            {
                ProdutoId = itemCarrinho.IdProduto,
                Produto = await produtoServices.GetProdutoAsync(itemCarrinho.IdProduto),
                Quantidade = itemCarrinho.Quantidade,
                ValorUnidade = itemCarrinho.Valor
            };

            return View(_item);
        }

        public IActionResult RemoverItem(int idProduto)
        {
            var carrinho = GetCarrinhoSessao();
            carrinho = RemoverItemCarrinho(idProduto, carrinho);
            HttpContext.Session.SetString(SessionCarrinho,
                    JsonConvert.SerializeObject(carrinho));
            return RedirectToAction("Index");
        }

        private Carrinho InsereItemNoCarrinho(ItemCarrinho itemCarrinho, Carrinho carrinho)
        {
            if(carrinho.Itens.Exists(a => a.IdProduto == itemCarrinho.IdProduto))
                carrinho.Itens.FirstOrDefault(a => a.IdProduto == itemCarrinho.IdProduto).Quantidade += itemCarrinho.Quantidade;
            else
                carrinho.Itens.Add(itemCarrinho);

            return carrinho;
        }

        private Carrinho EditarItemCarrinho(ItemCarrinho itemCarrinho, Carrinho carrinho)
        {
            if (carrinho.Itens.Exists(a => a.IdProduto == itemCarrinho.IdProduto))
                carrinho.Itens.FirstOrDefault(a => a.IdProduto == itemCarrinho.IdProduto).Quantidade = itemCarrinho.Quantidade;
            else
                carrinho.Itens.Add(itemCarrinho);

            return carrinho;
        }

        private Carrinho ReduzirItemCarrinho(int idProduto, Carrinho carrinho)
        {
            if (carrinho.Itens.Exists(a => a.IdProduto == idProduto))
                carrinho.Itens.FirstOrDefault(a => a.IdProduto == idProduto).Quantidade--;

            return carrinho;
        }

        private Carrinho RemoverItemCarrinho(int idProduto, Carrinho carrinho)
        {
            carrinho.Itens.Remove(carrinho.Itens.Find(a => a.IdProduto == idProduto));
            return carrinho;
        }

        public void ExcluirCarrinho()
        {
            HttpContext.Session.SetString(SessionCarrinho, "");
        }

        public IActionResult Remover()
        {
            ExcluirCarrinho();
            return Redirect("/");
        }

        [Authorize(Roles = "Consumidor")]
        public async Task<IActionResult> Finalizar()
        {
            var carrinho = GetCarrinhoSessao();
            var user = await loginServices.GetUsuarioLogadoAsync(User);

            var venda = new Venda()
            {
                Itens = ObterItensCarrinho(GetCarrinhoSessao()),
                DataVenda = DateTime.Now,
                IdUsuario = user.Id,
                Usuario = user,
                StatusVenda = StatusVenda.Aberta
            };

            venda = vendaServices.CreateVenda(venda);
            await produtoServices.AtualizarEstoque(venda.Itens);

            ExcluirCarrinho();

            return Redirect($"/Pedidos/Edit/{venda.Id}");
        }
    }
}

WebMVC/Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contratos;

namespace WebMVC.Controllers
{
    [Authorize(Roles = "Comerciante")]
    public class VendasController : Controller
    {
        private readonly IVendaServices vendaServices;
        private readonly ILoginServices loginServices;

        public VendasController(IVendaServices vendaServices, ILoginServices loginServices)
        {
            this.vendaServices = vendaServices;
            this.loginServices = loginServices;
        }

        public async Task<IActionResult> Index()
        {
            var user = await loginServices.GetUsuarioLogadoAsync(User);
            var pessoa = await loginServices.RetornaPessoaPeloUsuarioAsync(user);

            var itensvendidos = await vendaServices.ItensVendidos(pessoa as PessoaJuridica);

            return View(itensvendidos);
        }
    }
}

WebMVC/Controllers/VitrineLojaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Data;
using WebMVC.Models;
using Services.Contratos;

namespace WebMVC.Controllers
{
    public class VitrineLojaController : Controller
    {
        private readonly LojaDBContext _context;
        private readonly ILoginServices _services;
        private readonly IProdutoServices produtoServices;

        public VitrineLojaController(LojaDBContext context, ILoginServices services, IProdutoServices produtoServices)
        {
            _context = context;
            _services = services;
            this.produtoServices = produtoServices;
        }

        public async Task<IActionResult> Index()
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = await produtoServices.GetProdutosAsync(),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View(vitrine);
        }

        public async Task<IActionResult> IndexByIdComerciante(int? id)
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = produtoServices.GetProdutos(id.Value),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            var categoria = produtoServices.GetCategoriaProdutoByIdComerciante(id.Value);

            ViewBag.Categorias = _context.CategoriaProdutos.ToList().Where<CategoriaProduto>(c => c.IdComerciante == id.Value);

            return View(vitrine);
        }

        public async Task<IActionResult> IndexByIdCategoria(int? id)
        {
            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = produtoServices.GetProdutosByCategoria(id.Value),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.BuscarUsuarioPeloIDAsync(Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View(vitrine);
        }

        public ActionResult<List<Produto>> BuscarProduto(string nomeProduto)
        {
            var lista = _context.Produtos.Where(a => a.Nome.Contains(nomeProduto)).ToList();
            return new JsonResult(lista);
        }

        public async Task<IActionResult> ExibirBuscaProdutos(string nomeProduto)
        {
            nomeProduto = nomeProduto ?? "";

            var vitrine = new VitrineLojaViewModel()
            {
                Produtos = (await produtoServices.GetProdutosAsync()).Where(a => a.Nome.ToLower().Contains(nomeProduto.ToLower())).ToList(),
                CategoriaProdutos = await produtoServices.GetCategoriaProdutosAsync()
            };

            if (User.Identity.IsAuthenticated)
            {
                vitrine.User = await _services.GetUsuarioLogadoAsync(User);
            }

            ViewBag.Categorias = _context.CategoriaProdutos.ToList();

            return View("Index",vitrine);
        }

        public async Task<ActionResult> VerProduto(int? id)
        {
            if (id.HasValue)
            {
                var vitrine = new VitrineLojaViewModel()
                {
                    Produto = await produtoServices.GetProdutoAsync(id.Value)
                };

                vitrine.Produto.Categoria = produtoServices.GetCategoriaProduto(vitrine.Produto.IdCategoria);

                vitrine.Produto.Comerciante = produtoServices.GetComercianteProduto(vitrine.Produto.IdComerciante);

                if (vitrine.Produto != null) return View(vitrine.Produto); else return Redirect("/");
            }
            return Redirect("/");
        }
        
    }
}

WebMVC/Views/Carrinho/EditarItem.cshtml
@model Domain.Models.Item

<div class="container my-2 fill-content">
    <div class="row">
        <div class="col-sm">
            <h1><span class="badge badge-info">@Model.Produto.Marca</span> @Model.Produto.Nome</h1>
            <h4><a asp-action="IndexByIdComerciante" asp-controller="VitrineLoja" asp-route-id="@Model.Produto.Comerciante.Id">@Model.Produto.Comerciante.NomeFantasia</a> | @Model.Produto.Categoria.Nome</h4>
            <hr />
        </div>

    </div>
    <div class="row mt-2">
        <div class="col-sm-6">
            <div>
                <!-- Start Banner -->
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="false">
                    <ol class="carousel-indicators">
                        @{
                            var count = 0;
                            foreach (var imagem in Model.Produto.ImagensProduto)
                            {
                                <li data-target="#carouselExampleIndicators" data-slide-to="@count" class="active"></li>
                                count++;
                            }
                        }
                    </ol>
                    <div class="carousel-inner">
                        @{
                            count = 0;
                            foreach (var imagem in Model.Produto.ImagensProduto)
                            {
                                string classe;
                                @if (count == 0) { classe = "active"; }
                                else { classe = ""; }
                                <div class="carousel-item @classe">
                                    <a class="example-image-link" href="@imagem.UrlImagem" data-lightbox="@imagem.NomeImagem" data-title="@imagem.NomeImagem">
                                        <img class="d-block w-100" src="@imagem.UrlImagem" alt="@imagem.NomeImagem">
                                    </a>
                                </div>
                                count++;
                            }
                        }
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <!-- End Banner -->
            </div>
        </div>
        <div class="col-sm-3">
            <h3>R$ @Model.Produto.Preco</h3>
            <hr />
            <h6>Quantidade em Estoque: @Model.Produto.QuantidadeEstoque</h6>
        </div>
        <div class="col-sm-3">
            <div class="add-carrinho-box">
                <form>
                    <div class="form-group col-sm-8">
                        <label class="col-form-label">Quantidade:</label>
                        <input id="Quantidade" asp-for="Quantidade" class="form-control" type="number" min="1" onchange="BlockBuy()" />
                    </div>
                </form>
                @*<a asp-action="Index" asp-controller="Carrinho" id="Adicionar" class="btn btn-lg btn-success text-white" ><i class="fa fa-shopping-cart"></i> Adicionar ao Carrinho</a>*@
                <button class="btn btn-lg btn-success text-white" id="Adicionar"><i class="fa fa-shopping-cart"></i> Confirmar</button>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-sm-12">
            <div class="desc-produto">
                <label asp-for="Produto.Descricao"></label>
                <hr />
                <h2>@Model.Produto.Descricao</h2>
            </div>
        </div>
    </div>
</div>

<script>
    function ItemCarrinho(IdProduto, Quantidade, Valor) {
        this.IdProduto = IdProduto;
        this.Quantidade = Quantidade;
        this.Valor = Valor;
    }
    $("#Adicionar").click(function () {
        var item = new ItemCarrinho(@Model.Produto.Id, $("#Quantidade").val(),@Model.Produto.Preco);

        $.ajax({
            method: "POST",
            url: '@Url.Action("EditItem", "Carrinho")',
            data: { item }
        })
            .done(function (data) {
                //console.log(data);
                window.location.href = "@Url.Action("Index", "Carrinho")";
        });

    });
</script>
<script>
    function BlockBuy() {
        if (@Model.Produto.QuantidadeEstoque< ($("#Quantidade").val())) {
            $("#Adicionar").attr("disabled", "true");
            $("#Adicionar").addClass("blockbuy");
        } else {
            $(".blockbuy").removeAttr("disabled");
        }
    }
</script>

WebMVC/Views/Carrinho/Index.cshtml
@model IEnumerable<Domain.Models.Item>

@{
    ViewData["Title"] = "Carrinho";
}
<div class="details-bigbox container fill-content">
    <h1><i class="fa fa-shopping-cart"></i> Carrinho</h1>

    @{
        if (Model.Count() > 0)
        {
            <partial name="_Itens" model="@Model" />
            <a asp-action="Finalizar" asp-controller="Carrinho" class="btn btn-success"><i class="fa fa-dollar"></i> Comprar</a>
            <a asp-action="Remover" asp-controller="Carrinho" class="btn btn-danger"><i class="fa fa-trash"></i> Excluir Carrinho</a>
            <a asp-action="Index" asp-controller="VitrineLoja" class="btn btn-secondary"><i class="fa fa-shopping-cart"></i> Continuar Comprando</a>
        }
        else
        {
            <hr />
            <div class="alert alert-danger" role="alert">
                Você ainda não possui nenhum ítem no carrinho!
            </div>
        }
    }
</div>

<script>
    $(document).ready(function () {
        var _doc = $(document).height();
        var _win = $(window).height();

        if (_doc > _win) {
            $(".fill-content").css("height", "auto");
        }
    });
</script>

WebMVC/Views/Carrinho/Venda.cshtml
@model Domain.Models.Venda

@{
    ViewData["Title"] = "Venda";
}
<div class="fill-content">
    <h1>Venda</h1>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Venda">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="DataVenda" class="control-label"></label>
                    <input asp-for="DataVenda" class="form-control" />
                    <span asp-validation-for="DataVenda" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StatusVenda" class="control-label"></label>
                    <select asp-for="StatusVenda" class="form-control"></select>
                    <span asp-validation-for="StatusVenda" class="text-danger"></span>
                </div>
                <partial name="_Itens" model="@Model.Itens" />
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

WebMVC/Views/Carrinho/_Itens.cshtml
@model IEnumerable<Domain.Models.Item>

<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th>
                Valor Unitário
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="carrinho-img">
                    <img src="@item.Produto.ImagensProduto.First().UrlImagem" alt="" class="img-edit-prod" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produto.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    R$ @Html.DisplayFor(modelItem => item.Produto.Preco)
                </td>
                <td>
                    <div class="btn btn-group">
                        <a asp-action="EditarItem" asp-controller="Carrinho" asp-route-id="@item.ProdutoId" class="btn btn-dark"><i class="fa fa-edit"></i></a>
                        <a asp-action="RemoverItem" asp-controller="Carrinho" asp-route-idProduto="@item.ProdutoId" class="btn btn-danger"><i class="fa fa-remove"></i> </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    double total = 0.00;
    foreach (var item in Model)
    {
        total += item.Produto.Preco * item.Quantidade;
    }
<div class="col-sm-3 mb-3 carrinho-box">
    <h3>Valor Total:</h3>
    <hr />
    <h4>R$ @total</h4>
</div>
}