WebMVC/Controllers/AdminController.cs
using System.Linq;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Data;
using WebMVC.Models;
using Services.Contratos;
using System.Threading.Tasks;

namespace WebMVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly LojaDBContext context;
        private readonly IVendaServices vendaServices;
        private readonly ILoginServices loginServices;

        public AdminController(LojaDBContext context, IVendaServices vendaServices, ILoginServices loginServices)
        {
            this.context = context;
            this.vendaServices = vendaServices;
            this.loginServices = loginServices;
        }

        // GET: Admin
        public ActionResult Index()
        {
            var model = new AdministradorViewModel();
            model.Tarifas = context.Tarifas.ToList();
            return View(model);
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.Find(id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        [HttpPost]
        public ActionResult CadastroTarifa(Tarifa tarifa)
        {
            if (ModelState.IsValid)
            {
                context.Tarifas.Add(tarifa);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult CadastroTarifa()
        {
            return View();
        }

        public PartialViewResult ListaTarifas()
        {
            var model = new AdministradorViewModel();
            model.Tarifas = context.Tarifas.ToList();
            return PartialView("_listaTarifas", model.Tarifas);
        }
        
        public async Task<PartialViewResult> ListaVendas()
        {
            var model = new AdministradorViewModel();
            model.Vendas = await vendaServices.GetAllVendas();
            model.ObterLucro();

            return PartialView("_listaVendas", model.Vendas);
        }

        public async Task<PartialViewResult> AllVendas()
        {
            var model = new AdministradorViewModel();
            model.Vendas = await vendaServices.GetAllVendas();

            return PartialView("_allVendas", model.Vendas);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.Find(id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tarifa tarifa)
        {            
            if (id != tarifa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(tarifa);
                    context.SaveChanges();
                }
                catch 
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarifa = context.Tarifas.FirstOrDefault(t => t.Id == id);

            if (tarifa == null)
            {
                return NotFound();
            }

            return View(tarifa);
        }

        // POST: Admin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var tarifa = context.Tarifas.Find(id);
            context.Tarifas.Remove(tarifa);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));        
        }

        // GET: Admin/DeleteVenda/5
        public async Task<ActionResult> DeleteVenda(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await vendaServices.GetVendaByIdAsync(id.Value);

            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Admin/DeleteVenda/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteVenda(int id)
        {
            var venda = vendaServices.GetVendaById(id);
            await vendaServices.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebMVC/Controllers/UsuariosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Repository.Data;

namespace WebMVC.Controllers
{
    //[Authorize("Bearer")]
    public class UsuariosController : Controller
    {
        private readonly LojaDBContext _context;

        public UsuariosController(LojaDBContext context)
        {
            _context = context;
        }

        public ActionResult Buscar()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> BuscarPorNome(Usuario usuario)
        {
            var lista = await _context.Usuarios.Where(a => a.Username.Contains(usuario.Username)).ToListAsync();
            return new JsonResult(lista);
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            ViewBag.listaTipos = Enum.GetValues(typeof(TipoUsuario)).Cast<TipoUsuario>().ToList();

            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Email,Password,TipoUsuario")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                if(Convert.ToUInt32(usuario.TipoUsuario) == 0)
                {
                    return RedirectToAction("Create", "PessoaFisicas");
                }
                else
                {
                    if(Convert.ToUInt32(usuario.TipoUsuario) == 1)
                    {
                        return RedirectToAction("Create", "PessoaJuridicas");
                    }
                    else
                    {

                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Email,Password,TipoUsuario")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.listTipos = Enum.GetValues(typeof(TipoUsuario)).Cast<TipoUsuario>().ToList();
            return View(usuario);
        }

        // POST: Usuarios/EditarStatusAtivo/5
        [HttpPost]
        public async Task<IActionResult> EditarStatusAtivo(int id)
        {
            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);

            if (usuario.TipoUsuario == TipoUsuario.Comerciante)
            {
                var pj = await _context.PessoasJuridicas.FirstOrDefaultAsync(p => p.IdUsuario == usuario.Id);

                pj.StatusComerciante = StatusComerciante.Inativo;

                _context.PessoasJuridicas.Update(pj);
                await _context.SaveChangesAsync();
            }
            else
            {
                var pf = await _context.PessoasFisicas.FirstOrDefaultAsync(p => p.IdUsuario == usuario.Id);

                pf.StatusConsumidor = StatusConsumidor.Inativo;

                _context.PessoasFisicas.Update(pf);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Admin");
        }

        // POST: Usuarios/EditarStatusInativo/5
        [HttpPost]
        public async Task<IActionResult> EditarStatusInativo(int id)
        {
            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);

            if (usuario.TipoUsuario == TipoUsuario.Comerciante)
            {
                var pj = await _context.PessoasJuridicas.FirstOrDefaultAsync(p => p.IdUsuario == usuario.Id);

                pj.StatusComerciante = StatusComerciante.Ativo;

                _context.PessoasJuridicas.Update(pj);
                await _context.SaveChangesAsync();
            }
            else
            {
                var pf = await _context.PessoasFisicas.FirstOrDefaultAsync(p => p.IdUsuario == usuario.Id);

                pf.StatusConsumidor = StatusConsumidor.Ativo;

                _context.PessoasFisicas.Update(pf);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Admin");
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            if (usuario.TipoUsuario == TipoUsuario.Comerciante)
            {
                var pj = await _context.PessoasJuridicas.FirstOrDefaultAsync(m => m.IdUsuario == usuario.Id);
                string status = pj.StatusComerciante.ToString();
                ViewBag.Status = status;
            }
            else
            {
                var pf = await _context.PessoasFisicas.FirstOrDefaultAsync(m => m.IdUsuario == usuario.Id);
                string status = pf.StatusConsumidor.ToString();
                ViewBag.Status = status;
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        //Deleta o usuário e retorna para a tela principal do Administrador
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Admin");
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }
}

WebMVC/Views/Admin/CadastroTarifa.cshtml
@model Domain.Models.Tarifa

@{
    Layout = null;
}

<h1>Cadastro de Tarifa</h1>
<div>
    <h4>Tarifa</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CadastroTarifa">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label>Nome</label>
                    <input asp-for="Codigo" class="form-control" />
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Porcentagem" class="control-label"></label>
                    <input asp-for="Porcentagem" class="form-control" />
                    <span asp-validation-for="Porcentagem" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Valor Máximo</label>
                    <input asp-for="ValorMaximo" class="form-control" />
                    <span asp-validation-for="ValorMaximo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar Tarifa" class="btn btn-success" />
                    <a data-dismiss="modal" class="btn btn-primary text-white">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>

WebMVC/Views/Admin/Delete.cshtml
@model Domain.Models.Tarifa

@{
    Layout = null;
}

<h1>Deletar</h1>
<h3>Tens certeza que queres deletar este registro?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            Código:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-3">
            Porcentagem:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Porcentagem)
        </dd>
        <dt class = "col-sm-3">
            Valor Máximo:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.ValorMaximo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a data-dismiss="modal" class="btn btn-primary text-white">Voltar</a>
    </form>
</div>

WebMVC/Views/Admin/DeleteVenda.cshtml
@model Domain.Models.Venda

@{
    Layout = null;
}

<h1>Deletar</h1>
<h3>Tens certeza que queres deletar este registro?</h3>
<div>
    <h4>Venda</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            Usuário:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Usuario.Username)
        </dd class>
        <dt class = "col-sm-3">
            Data da Venda:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.DataVenda)
        </dd>
        <dt class = "col-sm-3">
            Status:
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.StatusVenda)
        </dd>
    </dl>
    
    <form asp-action="DeleteVenda">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a data-dismiss="modal" class="btn btn-primary text-white">Voltar</a>
    </form>
</div>

WebMVC/Views/Admin/Details.cshtml
@model Domain.Models.Tarifa

@{
    Layout = null;
}

<h1>Detalhes</h1>

<div>
    <h4>Tarifa</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Código
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Porcentagem)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Porcentagem)
        </dd>
        <dt class="col-sm-2">
            Valor Máximo
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValorMaximo)
        </dd>
    </dl>
</div>
<div>
    <a data-dismiss="modal" class="btn btn-danger">Voltar</a>
</div>

WebMVC/Views/Admin/Edit.cshtml
@model Domain.Models.Tarifa

@{
    Layout = null;
}

<h1>Editar</h1>
<div>
    <h4>Tarifa</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Codigo" class="control-label"></label>
                    <input asp-for="Codigo" class="form-control" />
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Porcentagem" class="control-label"></label>
                    <input asp-for="Porcentagem" class="form-control" />
                    <span asp-validation-for="Porcentagem" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ValorMaximo" class="control-label"></label>
                    <input asp-for="ValorMaximo" class="form-control" />
                    <span asp-validation-for="ValorMaximo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                    <a data-dismiss="modal" class="btn btn-danger text-white">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>

WebMVC/Views/Admin/Index.cshtml
@model WebMVC.Models.AdministradorViewModel
@using Domain.Models

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="details-bigbox container fill-content">
    <ul class="nav nav-tabs ss-a">
        <li class="nav-item">
            <a class="nav-link active bg-secondary" data-url="@Url.Action("ListaTarifas","Admin")" data-toggle="tab" href="" aria-selected="true">Tarifas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-secondary" data-url="@Url.Action("ListaVendas","Admin")" data-toggle="tab" href="" aria-selected="false">Ganhos sistemáticos</a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-secondary" data-url="@Url.Action("AllVendas", "Admin")" data-toggle="tab" href="" aria-selected="false">Vendas</a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-secondary" data-url="@Url.Action("Index", "Usuarios")" data-toggle="tab" href="" aria-selected="false">Usuários</a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-secondary" data-url="@Url.Action("Index","PessoaFisicas")" data-toggle="tab" href="" aria-selected="false">Consumidores</a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-secondary" data-url="@Url.Action("Index", "PessoaJuridicas")" data-toggle="tab" href="" aria-selected="false">Comerciantes</a>
        </li>
    </ul>
    <div id="listou">
        @await Html.PartialAsync("_listaTarifas.cshtml", Model.Tarifas)
    </div>
</div>

<div id="modal-container" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<script src="~/js/chamador.js"></script>
<link rel="stylesheet" type="text/css" href="~/css/custom.css" />

WebMVC/Views/Admin/_allVendas.cshtml
@model IEnumerable<Domain.Models.Venda>

<script src="~/js/callModal.js"></script>

<table class="table">
    <thead>
        <tr>
            <th>
                Consumidor
            </th>
            <th>
                Data da Venda
            </th>
            <th>
                Status
            </th>
            <th style="color:darkgreen">
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataVenda)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusVenda)
            </td>
            @if (item.StatusVenda.ToString() == "Concluida")
            {
                <td>
                    <button data-toggle="modal" class="btn btn-danger" disabled><i class="fa fa-trash"></i> Deletar</button>
                </td>
            }
            else
            {
                <td>
                    <a asp-action="DeleteVenda" data-target="#modal-container" data-toggle="modal" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa fa-trash"></i> Deletar</a>
                </td>
            }
        </tr>
        }
    </tbody>
</table>

WebMVC/Views/Admin/_listaTarifas.cshtml
@model IEnumerable<Domain.Models.Tarifa>

<script src="~/js/callModal.js"></script>

<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Porcentagem
            </th>
            <th>
                Valor Máximo
            </th>
            <th style="color:darkgreen">
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Porcentagem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorMaximo)
                </td>
                <td class="btn-group">
                    <a asp-action="Edit" data-target="#modal-container" data-toggle="modal" asp-route-id="@item.Id" class="btn btn-secondary"><i class="fa fa-edit"></i> Editar</a>
                    <a asp-action="Delete" data-target="#modal-container" data-toggle="modal" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa fa-trash"></i> Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="CadastroTarifa" data-target="#modal-container" data-toggle="modal" class="btn btn-success"><i class="fa fa-plus"></i> Nova Tarifa</a>
</div>

WebMVC/Views/Admin/_listaVendas.cshtml
@model IEnumerable<Domain.Models.Venda>

<table class="table">
    <thead>
        <tr>
            <th>Consumidor</th>
            <th>Data da Venda</th>
            <th>Lucro do Sistema</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var lucro = item.GetLucroSistema();
            if (item.StatusVenda == Domain.Models.StatusVenda.Concluida)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuario.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataVenda)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => lucro) R$
                    </td>
                    <td>
                </tr>
            }
        }
    </tbody>
</table>

<label>
    Valor somado total de todas as compras compradas e todas as vendas vendidas:
    @Model.Sum(m => m.StatusVenda == Domain.Models.StatusVenda.Concluida ? m.GetLucroSistema() : 0) R$
</label>